name: build and push postgis

on:
  push:
    branches:
      - master

jobs:
  build-image:
    name: build postgis images and push
    runs-on: ubuntu-latest

    steps:
      - name: install qemu
        run: docker run --rm --privileged hypriot/qemu-register

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: checkout
        uses: actions/checkout@v2

      - name: install buildx
        run: make install-buildx

      - name: build and push
        run: make build-latest
        env:
          BUILD_ARGS: "--push"
