name: build postgis docker images

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build-image:
    name: build postgis images and push
    runs-on: ubuntu-latest

    steps:
      - name: install qemu
        run: docker run --rm --privileged hypriot/qemu-register

      - name: checkout
        uses: actions/checkout@v2

      - name: install buildx
        run: make install-buildx

      - name: build and push
        run: make build-latest